name: Pruebas e integración de ramas de funcionalidad
on:
 push:
     branches:
         - 'feature/**'
         
jobs:
  tests:
    name: Pruebas unitarias
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, '(pr_to_dev)') && contains(github.ref,'feature') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Mezcla develop -> ${{ github.ref }}
      uses: tukasz/direct-merge-action@master
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: develop
         target-branch: ${{ github.ref }}
         commit-message: "Se realiza merge de develop en ${{ github.ref }}"
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Ejecutar build
      id: ejecutar-build
      run: |
          ng build
    - name:  Ejecutar pruebas y cubrimiento personalizado
      id: correr-pruebas
      run: |
          ng test --watch=false --code-coverage --source-map true
